// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSPPcu36xfi8xQsAkhepbVQbghp7H0iA',
    appId: '1:458479640546:web:09ab499e248719581723bb',
    messagingSenderId: '458479640546',
    projectId: 'pushmsg-bb8e9',
    authDomain: 'pushmsg-bb8e9.firebaseapp.com',
    storageBucket: 'pushmsg-bb8e9.firebasestorage.app',
    measurementId: 'G-TL09Q8TQZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrr6c__1MefXoCZlWUUf01-H1rpnwLmtA',
    appId: '1:458479640546:android:d3b2d764bd9de84b1723bb',
    messagingSenderId: '458479640546',
    projectId: 'pushmsg-bb8e9',
    storageBucket: 'pushmsg-bb8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOIeRDErUQwWzBQRhZjoPPjmNcJb-GefY',
    appId: '1:458479640546:ios:b74d6e249e112d1c1723bb',
    messagingSenderId: '458479640546',
    projectId: 'pushmsg-bb8e9',
    storageBucket: 'pushmsg-bb8e9.firebasestorage.app',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOIeRDErUQwWzBQRhZjoPPjmNcJb-GefY',
    appId: '1:458479640546:ios:b74d6e249e112d1c1723bb',
    messagingSenderId: '458479640546',
    projectId: 'pushmsg-bb8e9',
    storageBucket: 'pushmsg-bb8e9.firebasestorage.app',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZSPPcu36xfi8xQsAkhepbVQbghp7H0iA',
    appId: '1:458479640546:web:f4c3f06d8dc90ef51723bb',
    messagingSenderId: '458479640546',
    projectId: 'pushmsg-bb8e9',
    authDomain: 'pushmsg-bb8e9.firebaseapp.com',
    storageBucket: 'pushmsg-bb8e9.firebasestorage.app',
    measurementId: 'G-4WF4NJ7LR6',
  );
}
